[package]
name = "citus-membership-manager"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1"
bollard = "0.19"
tokio = { version = "1", features = ["macros", "signal"] }
tokio-postgres = "0.7"
tokio-stream = "0.1"
